export const teamImageMapping: { [key: string]: string } = {
    'default': 'https://resources.premierleague.com/presdfmierleague/badges/t1.png',
    'Manchester United FC': 'https://resources.premierleague.com/premierleague/badges/t1.png',
    'Arsenal FC': 'https://resources.premierleague.com/premierleague/badges/t3.png',
    'Manchester City FC': 'https://resources.premierleague.com/premierleague/badges/70/t43.png',
    'Aston Villa FC': 'https://resources.premierleague.com/premierleague/badges/t7.svg',
    'Brighton & Hove Albion FC': 'https://resources.premierleague.com/premierleague/badges/t36.svg',
    'Burnley FC': 'https://resources.premierleague.com/premierleague/badges/70/t90.png',
    'Chelsea FC': 'https://resources.premierleague.com/premierleague/badges/70/t8.png',
    'Crystal Palace FC': 'https://resources.premierleague.com/premierleague/badges/70/t31.png',
    'Everton FC': 'https://resources.premierleague.com/premierleague/badges/70/t11.png',
    'Fulham FC': 'https://resources.premierleague.com/premierleague/badges/70/t54.png',
    'Leeds United FC': 'https://resources.premierleague.com/premierleague/badges/t2.png',
    'Leicester City FC': 'https://resources.premierleague.com/premierleague/badges/70/t13.png',
    'Liverpool FC': 'https://resources.premierleague.com/premierleague/badges/70/t14.png',
    'Newcastle United FC': 'https://resources.premierleague.com/premierleague/badges/70/t4.png',
    'Sheffield United FC': 'https://resources.premierleague.com/premierleague/badges/70/t49.png',
    'Southampton FC': 'https://resources.premierleague.com/premierleague/badges/70/t20.png',
    'Tottenham Hotspur FC': 'https://resources.premierleague.com/premierleague/badges/70/t6.png',
    'West Bromwich Albion FC': 'https://resources.premierleague.com/premierleague/badges/70/t35.png',
    'West Ham United FC': 'https://resources.premierleague.com/premierleague/badges/70/t21.png',
    'Wolverhampton Wanderers FC': 'https://resources.premierleague.com/premierleague/badges/70/t39.png',
    'Stoke City FC': 'https://resources.premierleague.com/premierleague/badges/50/t110.png',
    'Swansea City FC': 'https://resources.premierleague.com/premierleague/badges/50/t80.png',
    'Sunderland AFC': 'https://resources.premierleague.com/premierleague/badges/50/t56.png',
    'Hull City AFC': 'https://resources.premierleague.com/premierleague/badges/50/t88.png',
    'Cardiff City FC': 'https://resources.premierleague.com/premierleague/badges/50/t97.png',
    'Norwich City FC': 'https://resources.premierleague.com/premierleague/badges/50/t45.png',
    'Queens Park Rangers FC': 'https://resources.premierleague.com/premierleague/badges/50/t52.png',
    'Watford FC': 'https://resources.premierleague.com/premierleague/badges/50/t57.png',
    'AFC Bournemouth': 'https://resources.premierleague.com/premierleague/badges/50/t91.png',
    'Middlesbrough FC': 'https://resources.premierleague.com/premierleague/badges/50/t25.png',
    'Huddersfield Town AFC': 'https://resources.premierleague.com/premierleague/badges/50/t38.png',
}
